quizes/urls.py
from django.urls import path,include
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_view

app_name = 'quizes'

urlpatterns = [ 
    path('', QuizListView.as_view(), name = 'main-view'),
    path('<int:pk>/', quiz_view, name='quiz-view'),
    path('<int:pk>/save', save_quiz_view, name='save_quiz-view'),
    path('<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
    url(r'^new/question', views.create_quiz, name='new-question'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile_view, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

schoolproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizes.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', views.LogoutView.as_view(), {'next_page':'/accounts/register/'}),
]

quizes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.

# class User(AbstractUser):
#     is_student = models.BooleanField('student status', default=False)
#     is_teacher = models.BooleanField('teacher status', default=False)

class Student(models.Model):
    admin_number = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return (str(self.admin_number))

class Teacher(models.Model):
    teacher_name = models.CharField(max_length=120)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

DIFF_CHOICES =(
    ('easy,', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField(default=1)
    time = models.IntegerField(help_text="durations of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="score in %")
    difficulty = models.CharField(max_length=10, choices=DIFF_CHOICES)
    # student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}--{self.topic}"

    def get_questions(self):
        return self.question_set.all()[:self.number_of_questions]

    @classmethod
    def search_project(cls, search_term):
        return cls.objects.filter(name__icontains=search_term).all()

    class Meta:
        verbose_name_plural = 'Quizes'



class Question(models.Model):
    text = models.CharField(max_length=100, default='')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE,)
    created = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()

class Answer(models.Model):
    text = models.CharField(max_length=120, default='')
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

  
class Result(models.Model):
    quiz= models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

quizes/forms.py
from django import forms
from django.db.models import fields
from .models import *
from django.forms import inlineformset_factory

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

class EditProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput( attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput( attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput( attrs={'class': 'form-control'}))
    
    class Meta:
        model =User
        fields = ['username', 'first_name', 'last_name', 'email', ]
        

class QuestionForm(forms.ModelForm):
    class Meta:
         model = Question
         fields = ['text']

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['name', 'topic', 'number_of_questions','required_score_to_pass','time','difficulty']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'correct']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['admin_number',]

quizes/views.py
from django.forms.models import inlineformset_factory
from django.shortcuts import redirect, render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from .models import *
from .forms import *
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required


# @login_required(login_url='/accounts/login/')
class QuizListView(ListView):
    model = Quiz 
    template_name = 'quizes/main.html'

@login_required(login_url='/accounts/login/')
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

@login_required(login_url='/accounts/login/')
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
     

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

def create_quiz(request):
    user =request.user
    if request.method=='POST':
        question_form = QuestionForm(request.POST)
        quiz_form = QuizForm(request.POST)
        answer_form = AnswerForm(request.POST, request.FILES, extra=3)
        if question_form.is_valid() and quiz_form.is_valid() and answer_form.is_valid():
            # question = question_form.save(commit=False)
            # quiz =quiz_form.save(commit=False)
            # answer = answer_form.save(commit =False)
            # question.user, quiz.user, answer.user = user
            # question.save()
            # quiz.save()
            # answer.save()
            quiz_form.save()
            quiz_form.save()
            answer_form.save()

            return redirect("quizes:main-view")

    else:
        question_form = QuestionForm()
        quiz_form = QuizForm()
        answer_form = AnswerForm()
    return render(request, 'quizes/question.html',{"question_form":question_form, "quiz_form":quiz_form, "answer_form":answer_form})


@login_required(login_url='/accounts/login/')
def profile_view(request):
    user = request.user
    user = User.objects.get(username = user.username)

    return render (request, 'quizes/profile.html', {"user":user})

@login_required(login_url='/accounts/login/')
def search(request):
    if 'quizes' in request.GET and request.GET["quizes"]:
        search_term = request.GET.get("quizes")
        searched_quizes = Quiz.search_project(search_term)
        message = f"{search_term}"

        return render(request, 'quizes/search.html',{"message":message,"quizes": searched_quizes})

    else:
        message = "You haven't searched for any quiz"
        return render(request, 'quizes/search.html',{"message":message})

@login_required(login_url='/accounts/login/')
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        user_form=EditProfileForm(request.POST, request.FILES,instance =request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.student)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # messages.success(request, f'Your profile was updated successfuly')
            return redirect("quizes:profile")
    else:
        user_form=EditProfileForm(instance =request.user)
        profile_form = ProfileUpdateForm(instance=request.user.student)

        context = {"user_form":user_form, "profile_form":profile_form, "user":user}
        return render(request, 'quizes/edit_profile.html', context)


# def dashboard(request):
#    if "user" in request.session:
#        user=request.session["user"]["username"]
#        context={"user":user}
#        return render(request,"dashboard.html",context)
#    else:
#        return HttpResponseNotFound("Page not found")

quizes/templates/navbar.html
<!-- <div class="navbar navbar-default navbar-fixed-top" role="navigation" style="background-color: #fb8500; color: antiquewhite;">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <a href="/" style="font-size: 25px; color: antiquewhite;"> Online</a>
      </div>
    
      <div class="nav navbar-nav navbar-right">
        <a  style="margin-right: 10px; font-size: 20px; color: antiquewhite;" href="">Post Question</a>
  
        <a  style="margin-right: 10px;font-size: 20px; color: antiquewhite;"href="">Profile </a>
        {% if user.is_authenticated %}
        <div class="nav navbar-nav navbar-right"><a style="margin-right: 10px;font-size: 20px; color: antiquewhite;" href="accounts/logout">Logout</a></div>
        {% else %}
        <ul>
          <li><a style="color: green; font-size: larger; font-weight: bold;">
            <a class='btn btn-default' href="/accounts/login">Login</a>
            <a class='btn btn-default' href="/accounts/register">Sign Up</a>
            {%endif%}
            </li>
        </ul>
  
      </div>
    </div>
  </div>
  </div> -->


  <!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Top navbar example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbar-static/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    
  </head>
  <body>
    
<nav class="navbar   navbar-fixed-top navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" style="font-size: 20px;" href="/">Home</a>
        </li>
        <li>
            <a  style="color: green; font-size: larger; font-weight: bold; color: aliceblue;" class='btn btn-default' href="/admin">Teacher</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> -->
      </ul>
      <form  action="{% url 'quizes:search' %}" type="search" class="d-flex" style="margin-left: 200px; width: 300px;">
        <input class="form-control me-2"   placeholder="Search Topics" aria-label="Search" name="quizes">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <div class="navbar navbar-expand-m"></div>
    <div class="nav navbar-nav navbar-right">
 
        {% if user.is_authenticated %}
       
        <a  style="margin-right: 10px; font-size: 20px; color: antiquewhite;" href="{% url 'quizes:new-question' %}">Question</a>
  
        <a  style="margin-right: 10px;font-size: 20px; color: antiquewhite; text-transform: capitalize;"href="{% url 'quizes:profile' %}">{{user.username}}</a>
        <div class="nav navbar-nav navbar-right"><a style="margin-right: 10px;font-size: 20px; color: antiquewhite;" href="accounts/logout">Logout</a></div>
        {% else %}
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            
          <li>
            <a  style="color: green; font-size: larger; font-weight: bold; color: aliceblue;" class='btn btn-default' href="/accounts/login">Student</a>
        </li>
        <li>
            <a  style="color: green; font-size: larger; font-weight: bold; color: aliceblue;" class='btn btn-default' href="/accounts/register">Sign Up</a>
        </li>
           
            {%endif%}
       
        </ul>
  
      </div>
  </div>
</nav>
  </body>
</html>