quizes/urls.py
from django.urls import path,include
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_view

app_name = 'quizes'

urlpatterns = [ 
    path('', QuizListView.as_view(), name = 'main-view'),
    path('<int:pk>/', quiz_view, name='quiz-view'),
    path('<int:pk>/save', save_quiz_view, name='save_quiz-view'),
    path('<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
    url(r'^new/question', views.create_quiz, name='new-question'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile_view, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

schoolproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizes.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', views.LogoutView.as_view(), {'next_page':'/accounts/register/'}),
]

quizes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.

# class User(AbstractUser):
#     is_student = models.BooleanField('student status', default=False)
#     is_teacher = models.BooleanField('teacher status', default=False)

class Student(models.Model):
    admin_number = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return (str(self.admin_number))

class Teacher(models.Model):
    teacher_name = models.CharField(max_length=120)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

DIFF_CHOICES =(
    ('easy,', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField(default=1)
    time = models.IntegerField(help_text="durations of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="score in %")
    difficulty = models.CharField(max_length=10, choices=DIFF_CHOICES)
    # student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}--{self.topic}"

    def get_questions(self):
        return self.question_set.all()[:self.number_of_questions]

    @classmethod
    def search_project(cls, search_term):
        return cls.objects.filter(name__icontains=search_term).all()

    class Meta:
        verbose_name_plural = 'Quizes'



class Question(models.Model):
    text = models.CharField(max_length=100, default='')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE,)
    created = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()

class Answer(models.Model):
    text = models.CharField(max_length=120, default='')
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

  
class Result(models.Model):
    quiz= models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

quizes/forms.py
from django import forms
from django.db.models import fields
from .models import *
from django.forms import inlineformset_factory

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

class EditProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput( attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput( attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput( attrs={'class': 'form-control'}))
    
    class Meta:
        model =User
        fields = ['username', 'first_name', 'last_name', 'email', ]
        

class QuestionForm(forms.ModelForm):
    class Meta:
         model = Question
         fields = ['text']

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['name', 'topic', 'number_of_questions','required_score_to_pass','time','difficulty']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'correct']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['admin_number',]

quizes/views.py
from django.forms.models import inlineformset_factory
from django.shortcuts import redirect, render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from .models import *
from .forms import *
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required


# @login_required(login_url='/accounts/login/')
class QuizListView(ListView):
    model = Quiz 
    template_name = 'quizes/main.html'

@login_required(login_url='/accounts/login/')
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

@login_required(login_url='/accounts/login/')
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
     

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

def create_quiz(request):
    user =request.user
    if request.method=='POST':
        question_form = QuestionForm(request.POST)
        quiz_form = QuizForm(request.POST)
        answer_form = AnswerForm(request.POST, request.FILES, extra=3)
        if question_form.is_valid() and quiz_form.is_valid() and answer_form.is_valid():
            # question = question_form.save(commit=False)
            # quiz =quiz_form.save(commit=False)
            # answer = answer_form.save(commit =False)
            # question.user, quiz.user, answer.user = user
            # question.save()
            # quiz.save()
            # answer.save()
            quiz_form.save()
            quiz_form.save()
            answer_form.save()

            return redirect("quizes:main-view")

    else:
        question_form = QuestionForm()
        quiz_form = QuizForm()
        answer_form = AnswerForm()
    return render(request, 'quizes/question.html',{"question_form":question_form, "quiz_form":quiz_form, "answer_form":answer_form})


@login_required(login_url='/accounts/login/')
def profile_view(request):
    user = request.user
    user = User.objects.get(username = user.username)

    return render (request, 'quizes/profile.html', {"user":user})

@login_required(login_url='/accounts/login/')
def search(request):
    if 'quizes' in request.GET and request.GET["quizes"]:
        search_term = request.GET.get("quizes")
        searched_quizes = Quiz.search_project(search_term)
        message = f"{search_term}"

        return render(request, 'quizes/search.html',{"message":message,"quizes": searched_quizes})

    else:
        message = "You haven't searched for any quiz"
        return render(request, 'quizes/search.html',{"message":message})

@login_required(login_url='/accounts/login/')
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        user_form=EditProfileForm(request.POST, request.FILES,instance =request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.student)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # messages.success(request, f'Your profile was updated successfuly')
            return redirect("quizes:profile")
    else:
        user_form=EditProfileForm(instance =request.user)
        profile_form = ProfileUpdateForm(instance=request.user.student)

        context = {"user_form":user_form, "profile_form":profile_form, "user":user}
        return render(request, 'quizes/edit_profile.html', context)


# def dashboard(request):
#    if "user" in request.session:
#        user=request.session["user"]["username"]
#        context={"user":user}
#        return render(request,"dashboard.html",context)
#    else:
#        return HttpResponseNotFound("Page not found")

quizes/templates/quizes/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<!-- CSS only -->

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
    {% include 'navbar.html' %}
  </head>
  <body style="background-color: #005f73;">
    
        {% block content %}
        {% endblock content %}
   
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

quizes/templates/quizes/edit_profile.html
{% extends 'quizes/base.html' %}
{% load bootstrap3 %} {% load static %}

{% block content %}
<div class="container-fluid" style="padding-top: 90px; color: antiquewhite; font-size: 25px;font-family: Assistant;">
    <div class="row">
        
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h2 class="text-center">Update for {{user.username}}</h2>
            <div class="content-section">
               
                <div class="media">
                    
                    <div class="media-body">
                        <h2 class="account-heading">{{user.username}}</h2>
                    </div>
                </div>

                <div class="form-group">
                    <form method="POST">

                        {% csrf_token %}

                        {{ user_form.as_p }}
                        {{ profile_form.as_p }}
                        <button type="submit" class="btn btn-primary">Update Profile</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
</div>


{% endblock %}
{% block scripts %} {{block.super}}
<script type="text/javascript" src="{% static 'js/main.js '%}"></script>
{% endblock %}

quizes/templates/quizes/formset.html
{% load static %}
{{ formset.management_form }}
{% for form in formset.forms %}
  <table id="duration" class="table table-striped table-inline table-responsive">
      {% if forloop.first %}
          <thead>
          <tr>
              {% for field in form.visible_fields %}
                  <th> {{ field.label }} </th>
              {% endfor %}
          </tr>
          </thead>
      {% endif %}
      <tbody>
          <tr class="formset_row">
              {% for field in form.visible_fields %}
                  <td>
                      {# Include the hidden fields in the form #}
                      {% if forloop.first %}
                          {% for hidden in form.hidden_fields %}
                              {{ hidden }}
                          {% endfor %}
                      {% endif %}
                      {{ field.errors.as_ul }}
                      {{ field }}
                  </td>
              {% endfor %}
          </tr>
      </tbody>
  </table>
{{ form.media }}
{% endfor %}

quizes/templates/quizes/main.html
{% extends 'quizes/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block scripts %}
<script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock %}

{% block content %}

<div class="container-fluid" >
  <div class="container" style="color: darkgray;">
    <div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Begin Test</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body" id="modal-body-confirm">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
            <button type="button" id="start-button" class="btn btn-success">Yes</button>
          </div>
        </div>
      </div>
    </div>

    <div class="h1">Topics:</div>
    <hr>

    {% for obj in object_list %}
    <button class="btn btn-link modal-button" style="font-size: 25px;" data-pk="{{obj.pk}}" data-quiz="{{obj.name}}"
      data-question="{{obj.number_of_questions}}" data-difficulty="{{obj.difficulty}}" data-time="{{obj.time}}"
      data-pass="{{obj.required_score_to_pass}}" data-toggle="modal" data-target="#quizStartModal">
      <span class="text">
        <ol style="list-style: none; color: honeydew; font-size: larger;">
          <li> {{obj.name}}</li>
        </ol>
      </span>
    </button>
    <hr>
    <br>
    {% endfor %}
  </div>
  <div class="footer"></div>
</div>

{% endblock %}

quizes/templates/quizes/profile.html
{% extends 'quizes/base.html' %}
{% load bootstrap3 %} {% load static %}
<link href="https://fonts.googleapis.com/css2?family=Assistant:wght@300&family=Nanum+Gothic:wght@700&display=swap"
  rel="stylesheet">

{% block content %}
<div class="container-fluid" style="padding-top: 60px;font-family: Assistant;">
  <div class="container" style="padding-top: 70px;">
    <div class="row">
      <div class="col-md-6" style="color: antiquewhite;">
        <h1>Student Details</h1>
        <h3> Name: <span class="text text-capitalize">{{user.first_name}} {{user.last_name}}</span></h3>
        <p style="font-size: 20px;">Email :{{user.email}}</p>
        <p style="font-size: 20px;">Admin Number : {{user.student.admin_number}}</p>
        <hr>
        <button class="btn btn-outline-success"> <a href="{% url 'quizes:edit_profile' %}"> Edit Profile</a> </button>
      </div>

    </div>
  </div>

</div>

{% endblock %}
{% block scripts %} {{block.super}}
<script type="text/javascript" src="{% static 'js/main.js '%}"></script>
{% endblock %}

quizes/templates/quizes/question.html
{% extends 'quizes/base.html' %}
{% load bootstrap4 %} {% load static %}

{% block content %}
<div class="container-fluid" style="padding-top: 90px; color: antiquewhite; font-size: 25px;font-family: Assistant;">
            <div class="content-section">
                <div class="form-group">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4"><h2>Quiz</h2>
                                {{ quiz_form }}</div>
                            <div class="col-md-4"> <h2>Questions</h2>
                                {{ question_form}}</div>
                            <div class="col-md-4"> <h2>Answers</h2>
                                {{answer_form }}</div>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div> 
</div>
</div>


{% endblock %}
{% block scripts %} {{block.super}}
<script type="text/javascript" src="{% static 'js/main.js '%}"></script>
{% endblock %}

quizes/templates/quizes/quiz.html
{% extends 'quizes/base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block title %}
{{obj.name}}
{% endblock title %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script> 
{% endblock scripts %}

{% block content %}
<div class="container">
    <div class="row" style="align-items: center;">
       
        <div class="col-md-6">
            <h1>Questions</h1>
            <b>Topic: {{obj.name}}</b>
            <p>Pass mark: {{obj.required_score_to_pass}}%</p>

            <form id="quiz-form" class="mt-3 mb-3">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        <div id="quiz-box" style="font-size: large; font-family: 'Courier New', Courier, monospace; list-style: decimal-leading-zero;"></div>
                    </div>
                </div>
                
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
            </form>
        </div>
        <div class="col-md-6">
            <div id="score-box"></div>
            <div id="result-box"></div>
        </div>
    </div>
    
    
    
   
   
</div>

{% endblock content %}

  

quizes/templates/quizes/search.html
{% extends 'quizes/base.html' %}
{% load bootstrap3 %} {% load static %}

{% block content %}
<div class="continer-fluid" style="padding-top: 90px; background-color: #023047;font-family: Assistant;">
  <div class="container" style="padding-top: 100px; color: antiquewhite;">

    <div class="row">
      {% if quizes%}
      <h2>Found {{ quizes|length }} topics</h2>
      {% else %}
      <h2> Found 0 topics for the search term {{message}}</h2>
      {% endif %}

    </div>

    <div class="row">
      <div class="col-md-3"></div>
      {% if quizes %}
      {% for quiz in quizes %}
      
      <div class=" col-md-6">
        <div class="panel">
          <div class="panel-header">
            <a href="{% url 'quizes:quiz-data-view' quiz.id %}"><h1 style="color: blue;">{{quiz.name}}</h1></a>
            
          </div>
          <!-- <div class="panel-body"><img src="{{project.project_image.url}}" style="height: 400px; width: 500px;" alt="">
            <p style="color: blue;">{{project.project_description}}</p>
          </div> -->
        </div>
      </div>
      <div class="col-md-3"></div>
      {% endfor %}
      {% endif %}
    </div>
  </div>

</div>
{% endblock %}
{% block scripts %} {{block.super}}
<script type="text/javascript" src="{% static 'js/main.js '%}"></script>
{% endblock %}